import * as mongoose from 'mongoose';

export const ClanMemberSchema = new mongoose.Schema({
  player_code: String,
  country_code: String,
  max_stage: Number,
  raid_wildcard_count: Number,
  current_card_currency: Number,
  name: String,
  total_raid_player_xp: String,
  player_raid_level: String,
  summon_level: Number,
  total_card_level: String,
  role: String,
  weekly_ticket_count: String,
  titan_cards: [
    {
      titan_id: String,
      level: Number,
      quantity_received: Number,
      quantity_spent: Number
    }
  ],
  raid_research_tree: {
    ArmorDamage: Number,
    BodyDamage: Number,
    ChestDamage: Number,
    HeadDamage: Number,
    LimbDamage: Number,
    RaidEnemy1Damage: Number,
    RaidEnemy2Damage: Number,
    RaidEnemy3Damage: Number,
    RaidEnemy4Damage: Number,
    RaidEnemy5Damage: Number,
    RaidEnemy6Damage: Number,
    RaidEnemy7Damage: Number,
    RaidEnemy8Damage: Number
  },
  raid_research_bonuses: {
    RaidBaseDamage: Number,
    AfflictionBaseDamage: Number,
    BurstBaseDamage: Number,
    ArmorBaseDamage: Number,
    BodyBaseDamage: Number,
    HeadBaseDamage: Number,
    LimbBaseDamage: Number,
    TorsoBaseDamage: Number,
    HeadArmorBaseDamage: Number,
    LimbArmorBaseDamage: Number,
    TorsoArmorBaseDamage: Number,
    HeadBodyBaseDamage: Number,
    LimbBodyBaseDamage: Number,
    TorsoBodyBaseDamage: Number,
    Enemy1BaseDamage: Number,
    Enemy2BaseDamage: Number,
    Enemy3BaseDamage: Number,
    Enemy4BaseDamage: Number,
    Enemy5BaseDamage: Number,
    Enemy6BaseDamage: Number,
    Enemy7BaseDamage: Number,
    Enemy8BaseDamage: Number,
    Enemy1AfflictionBaseDamage: Number,
    Enemy2AfflictionBaseDamage: Number,
    Enemy3AfflictionBaseDamage: Number,
    Enemy4AfflictionBaseDamage: Number,
    Enemy5AfflictionBaseDamage: Number,
    Enemy6AfflictionBaseDamage: Number,
    Enemy7AfflictionBaseDamage: Number,
    Enemy8AfflictionBaseDamage: Number,
    Enemy1BurstBaseDamage: Number,
    Enemy2BurstBaseDamage: Number,
    Enemy3BurstBaseDamage: Number,
    Enemy4BurstBaseDamage: Number,
    Enemy5BurstBaseDamage: Number,
    Enemy6BurstBaseDamage: Number,
    Enemy7BurstBaseDamage: Number,
    Enemy8BurstBaseDamage: Number
  },
  loyalty_level: String,
  daily_raid_tickets: String,
  previous_rank: String,
  cards: [
    {
      level: Number,
      quantity_received: Number,
      quantity_spent: Number,
      skill_name: String
    }
  ],
  equipment_set: [String]
});